// PresetWriter — generates the files that make up one MSYS2 agent preset, and
// installs or removes them.
//
// The generated composition is the successor to the old two-plane MSYS2 setup
// (a host-plane profiles/web/cordis.patch.yml plus a launch-msys-profile.cmd
// that pre-pended MSYS2's usr\bin to PATH). None of that is needed any more:
// the preset carries its own shell argv, so the host launch environment is
// irrelevant and the user just runs `npx @deepseek-ai/dsh web` and picks a
// flavour from the roster.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Dsh.Msys2Installer
{
    /// <summary>What an install produced, for reporting in the GUI.</summary>
    public sealed class InstallResult
    {
        public Msys2Flavour Flavour;
        public string PresetDir;
        public List<string> Written = new List<string>();
    }

    public static class PresetWriter
    {
        public const string CompositionFileName = "agent.cordis.yml";
        public const string MetadataFileName = "preset.yml";
        public const string ReadmeFileName = "README.md";
        public const string ShimExeName = "msys2_shell_shim.exe";

        /// <summary>Single-quote a YAML scalar, doubling any embedded quote.</summary>
        public static string YamlQuote(string text)
        {
            return "'" + text.Replace("'", "''") + "'";
        }

        /// <summary>
        /// Forward slashes for a path that goes into YAML consumed on Windows.
        /// Node, cmd.exe and bash all accept them, and they avoid the escaping
        /// questions a backslash raises in any YAML scalar.
        /// </summary>
        public static string Posix(string windowsPath)
        {
            return windowsPath.Replace('\\', '/');
        }

        /// <summary>The picker metadata written beside a preset's composition.</summary>
        public static string RenderMetadata(Msys2Flavour flavour)
        {
            var sb = new StringBuilder();
            sb.Append("name: ").Append(YamlQuote("MSYS2 · " + flavour.Key)).Append('\n');
            sb.Append("description: ")
              .Append(YamlQuote(flavour.Label + " — " + flavour.Blurb))
              .Append('\n');
            return sb.ToString();
        }

        /// <summary>
        /// The agent composition for one flavour.
        ///
        /// `shimExe` is baked in as an absolute path on purpose: presets are
        /// discovered from the harness home, so a relative reference would
        /// resolve against the wrong base.
        /// </summary>
        public static string RenderComposition(Msys2Flavour flavour, string shellCmd, string shimExe)
        {
            string shellPosix = Posix(shellCmd);
            string shimPosix = Posix(shimExe);
            string rootPosix = Posix(Path.GetDirectoryName(Path.GetFullPath(shellCmd)));
            string msystem = flavour.Msystem;
            string flag = flavour.ShellFlag;

            // Built with Append rather than interpolation: this compiler is
            // csc 4.8, which is C# 5 and has no interpolated strings.
            var sb = new StringBuilder();

            sb.Append("# MSYS2 agent preset — ").Append(flavour.Label).Append('\n');
            sb.Append("#\n");
            sb.Append("# GENERATED by the DSH MSYS2 installer. Edit the installer's template rather\n");
            sb.Append("# than this file: reinstalling overwrites it.\n");
            sb.Append("#\n");
            sb.Append("# Every command runs through msys2_shell.cmd:\n");
            sb.Append("#\n");
            sb.Append("#   msys2_shell.cmd -defterm -no-start -use-full-path ").Append(flag).Append(" -here -c \"<command>\"\n");
            sb.Append("#\n");
            sb.Append("# WHY THERE IS A SHIM .EXE\n");
            sb.Append("#\n");
            sb.Append("# The pwsh executor spawns ONE fixed argv per command:\n");
            sb.Append("#\n");
            sb.Append("#   [<pwshPath>, \"-NoLogo\", \"-NoProfile\", \"-NonInteractive\", \"-Command\", <command>]\n");
            sb.Append("#\n");
            sb.Append("# with no shell involved, and `pwshPath` is used verbatim as argv[0] of a\n");
            sb.Append("# direct CreateProcessW. Two consequences force the shim:\n");
            sb.Append("#\n");
            sb.Append("#   1. argv[0] cannot be a .cmd/.bat — Node's spawn rejects those with EINVAL.\n");
            sb.Append("#      So `pwshPath` cannot simply be msys2_shell.cmd.\n");
            sb.Append("#   2. The command arrives with a PowerShell encoding preamble prepended,\n");
            sb.Append("#      which bash cannot parse.\n");
            sb.Append("#\n");
            sb.Append("# `").Append(ShimExeName).Append("` is a real executable that closes both gaps: it strips\n");
            sb.Append("# the preamble, writes the command to a temporary shell script, and runs\n");
            sb.Append("# the msys2_shell.cmd invocation above with that script as the command. It\n");
            sb.Append("# propagates the exit code verbatim, which is what makes the tool layer's\n");
            sb.Append("# `[exit code: N]` reporting meaningful. Its behaviour is configured by two\n");
            sb.Append("# environment variables, so the same binary serves every flavour:\n");
            sb.Append("#\n");
            sb.Append("#   DSH_MSYS2_SHELL_CMD = ").Append(shellPosix).Append('\n');
            sb.Append("#   DSH_MSYS2_MSYSTEM   = ").Append(msystem).Append('\n');
            sb.Append("#\n");
            sb.Append("# WHY THE HOST NEEDS danger-full-access\n");
            sb.Append("#\n");
            sb.Append("# MSYS2 binaries cannot start under the Windows ACL sandbox. `usr\\bin` loads\n");
            sb.Append("# `msys-2.0.dll`, whose startup creates the per-user named section\n");
            sb.Append("# `CreateFileMapping S-1-5-21-<user>-1001.1`; a write-restricted token denies it\n");
            sb.Append("# with Win32 error 5, so `bash.exe` terminates before running a single command:\n");
            sb.Append("#\n");
            sb.Append("#     bash.exe: *** fatal error - CreateFileMapping S-1-5-21-...-1001.1,\n");
            sb.Append("#     Win32 error 5.  Terminating.\n");
            sb.Append("#\n");
            sb.Append("# That is not specific to this preset — msys2_shell.cmd and ls.exe fail the\n");
            sb.Append("# same way — so this preset pins the unconfined permission preset below.\n");
            sb.Append("# Treat a session on this preset as shell access that no file-write boundary\n");
            sb.Append("# mediates.\n");
            sb.Append('\n');

            // ── permissions ────────────────────────────────────────────────────
            sb.Append("- id: sandbox-policy\n");
            sb.Append("  name: '@deepseek-ai/dsh-sandbox-policy'\n");
            sb.Append("  config:\n");
            sb.Append("    mode: danger-full-access\n");
            sb.Append("    workspaceRoot: !!js process.cwd()\n");
            sb.Append('\n');
            sb.Append("- id: approval\n");
            sb.Append("  name: '@deepseek-ai/dsh-user-approval'\n");
            sb.Append("  config:\n");
            sb.Append("    policy: never\n");
            sb.Append('\n');

            // ── persona ────────────────────────────────────────────────────────
            // {{model}} and {{cwd}} are DSH's own template tokens and must
            // survive into the file unchanged.
            sb.Append("- id: persona\n");
            sb.Append("  name: '@deepseek-ai/dsh-persona'\n");
            sb.Append("  config:\n");
            sb.Append("    text: |-\n");
            sb.Append("      You are a coding agent powered by the {{model}} model, running on the DeepSeek Harness on Windows. Your working directory is {{cwd}}.\n");
            sb.Append('\n');
            sb.Append("      Your command tool is `pwsh`, but it does NOT run PowerShell. Every command is handed to MSYS2's `").Append(flavour.Key).Append("` environment through `msys2_shell.cmd`, so the command string must be **bash**, not PowerShell: forward slashes, `$VAR` instead of `$env:VAR`, `export VAR=value` instead of `$env:VAR = ...`, and POSIX utilities rather than cmdlets. A command that is valid PowerShell will almost certainly fail as bash.\n");
            sb.Append('\n');
            sb.Append("      MSYS2 lives at `").Append(rootPosix).Append("` and this session's environment is ").Append(msystem).Append(". Toolchain executables come from that environment: `uname -s` reports the MSYS2 kernel, and compilers are on PATH directly (`gcc --version`, `clang --version`). To confirm which environment you are in, run `echo $MSYSTEM`.\n");
            sb.Append('\n');
            sb.Append("      Each call is a fresh shell, so state does not persist between calls — pass `workdir` rather than using `cd`, and never rely on an exported variable surviving into the next call.\n");
            sb.Append('\n');
            sb.Append("      This session runs unconfined (`danger-full-access`). That is a hard requirement of the MSYS2 runtime, not a preference: `msys-2.0.dll` needs a per-user named section that the Windows write-restricted token denies, so every MSYS2 program fails at startup under any confined mode. Because no file-write boundary is enforced, do not rely on the sandbox to catch a mistake: stay inside the workspace unless a task genuinely requires otherwise, and never run a destructive command without a clear reason.\n");
            sb.Append('\n');
            sb.Append("      If a command fails with `CreateFileMapping ... Win32 error 5`, the session is confined and the MSYS2 runtime cannot start at all — report that instead of working around it.\n");
            sb.Append('\n');
            sb.Append("- id: agent-instructions\n");
            sb.Append("  name: '@deepseek-ai/dsh-agent-instructions'\n");
            sb.Append("  config:\n");
            sb.Append("    maxBytes: 65536\n");
            sb.Append('\n');

            // ── shell ──────────────────────────────────────────────────────────
            sb.Append("# ── shell ───────────────────────────────────────────────────────────────────\n");
            sb.Append("#\n");
            sb.Append("# The `pwsh` tool is deliberately KEPT as the model-facing name, and the\n");
            sb.Append("# executor behind it is retargeted at the shim through `pwshPath`. The base\n");
            sb.Append("# bundle mounts exactly one shell stack per platform (`ctx.shell` is a single\n");
            sb.Append("# process-wide provider), and on win32 that is the pwsh pair — so reusing the\n");
            sb.Append("# pwsh tool is what lets this preset carry the MSYS2 shell WITHOUT any\n");
            sb.Append("# host-plane patch file or custom launcher. The tool's name is a label;\n");
            sb.Append("# `pwshPath` is what actually runs.\n");
            sb.Append('\n');
            sb.Append("- id: pwsh-sandbox\n");
            sb.Append("  name: '@deepseek-ai/dsh-pwsh-sandbox'\n");
            sb.Append("  disabled: false\n");
            sb.Append("  config:\n");
            sb.Append("    pwshPath: ").Append(shimPosix).Append('\n');
            sb.Append('\n');
            sb.Append("- id: tool-pwsh\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-pwsh'\n");
            sb.Append("  disabled: false\n");
            sb.Append('\n');

            // ── filesystem ─────────────────────────────────────────────────────
            sb.Append("# ── filesystem ──────────────────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: tool-fs\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-fs'\n");
            sb.Append('\n');
            sb.Append("- id: tool-fs-search\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-fs-search'\n");
            sb.Append("  config:\n");
            sb.Append("    sampleOverCapGlobResults: false\n");
            sb.Append('\n');

            // ── background jobs ────────────────────────────────────────────────
            sb.Append("# ── background jobs ────────────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: tool-jobs\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-jobs'\n");
            sb.Append('\n');

            // ── goals ──────────────────────────────────────────────────────────
            sb.Append("# ── goals ───────────────────────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: command-goal\n");
            sb.Append("  name: '@deepseek-ai/dsh-command-goal'\n");
            sb.Append('\n');
            sb.Append("- id: tool-goal\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-goal'\n");
            sb.Append('\n');

            // ── plan mode ──────────────────────────────────────────────────────
            sb.Append("# ── plan mode ───────────────────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: planning\n");
            sb.Append("  name: cordis:group\n");
            sb.Append("  group: true\n");
            sb.Append("  isolate:\n");
            sb.Append("    planMode: true\n");
            sb.Append("  config:\n");
            sb.Append("    - id: plan-mode\n");
            sb.Append("      name: '@deepseek-ai/dsh-plan-mode'\n");
            sb.Append('\n');

            // ── compaction ─────────────────────────────────────────────────────
            sb.Append("# ── compaction ──────────────────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: compaction\n");
            sb.Append("  name: cordis:group\n");
            sb.Append("  group: true\n");
            sb.Append("  isolate:\n");
            sb.Append("    compaction: true\n");
            sb.Append("    toolResultPruner: true\n");
            sb.Append("  config:\n");
            sb.Append("    - id: compaction-basic\n");
            sb.Append("      name: '@deepseek-ai/dsh-compaction-basic'\n");
            sb.Append('\n');
            sb.Append("    - id: command-compact\n");
            sb.Append("      name: '@deepseek-ai/dsh-command-compact'\n");
            sb.Append('\n');
            sb.Append("    - id: tool-result-pruner\n");
            sb.Append("      name: '@deepseek-ai/dsh-compaction-tool-result-pruner'\n");
            sb.Append("      config:\n");
            sb.Append("        thresholdChars: 8192\n");
            sb.Append("        headChars: 4096\n");
            sb.Append("        tailChars: 1024\n");
            sb.Append('\n');

            // ── delegation ─────────────────────────────────────────────────────
            sb.Append("# ── delegation and workflows ────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: delegation\n");
            sb.Append("  name: cordis:group\n");
            sb.Append("  group: true\n");
            sb.Append("  isolate:\n");
            sb.Append("    workflowEngine: true\n");
            sb.Append("  config:\n");
            sb.Append("    - id: tool-subagent-control\n");
            sb.Append("      name: '@deepseek-ai/dsh-tool-subagent-control'\n");
            sb.Append('\n');
            sb.Append("    - id: tool-subagent-list-agents\n");
            sb.Append("      name: '@deepseek-ai/dsh-tool-subagent-control/list-agents'\n");
            sb.Append('\n');
            sb.Append("    - id: tool-subagent\n");
            sb.Append("      name: '@deepseek-ai/dsh-tool-subagent'\n");
            sb.Append("      config:\n");
            sb.Append("        provider: spawn\n");
            sb.Append("        toolName: subagent\n");
            sb.Append("        modelSelectionSettings: true\n");
            sb.Append("        backgroundMode: continuable\n");
            sb.Append('\n');
            sb.Append("    - id: tool-subagent-fork\n");
            sb.Append("      name: '@deepseek-ai/dsh-tool-subagent'\n");
            sb.Append("      config:\n");
            sb.Append("        provider: fork\n");
            sb.Append("        toolName: subagent_fork\n");
            sb.Append("        backgroundMode: continuable\n");
            sb.Append('\n');
            sb.Append("    - id: workflow-worker-thread\n");
            sb.Append("      name: '@deepseek-ai/dsh-workflow-worker-thread'\n");
            sb.Append("      config:\n");
            sb.Append("        provider: spawn\n");
            sb.Append('\n');
            sb.Append("    - id: tool-workflow\n");
            sb.Append("      name: '@deepseek-ai/dsh-tool-workflow'\n");
            sb.Append('\n');
            sb.Append("    - id: tool-ralph\n");
            sb.Append("      name: '@deepseek-ai/dsh-tool-ralph'\n");
            sb.Append("      config:\n");
            sb.Append("        subagentProvider: spawn\n");
            sb.Append("        maxRounds: 64\n");
            sb.Append('\n');

            // ── model-facing rows ──────────────────────────────────────────────
            sb.Append("# ── remaining model-facing rows ─────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: tool-ask-user\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-ask-user'\n");
            sb.Append('\n');
            sb.Append("- id: tool-todo\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-todo'\n");
            sb.Append("  config:\n");
            sb.Append("    allowParallelInProgress: true\n");
            sb.Append('\n');
            sb.Append("- id: tool-web\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-web'\n");
            sb.Append("  config:\n");
            sb.Append("    fetch: true\n");
            sb.Append("    searchTimeoutMs: 60000\n");
            sb.Append('\n');

            // ── skills ─────────────────────────────────────────────────────────
            sb.Append("# ── skills ──────────────────────────────────────────────────────────────────\n");
            sb.Append('\n');
            sb.Append("- id: tool-skill\n");
            sb.Append("  name: '@deepseek-ai/dsh-tool-skill'\n");

            return sb.ToString();
        }

        /// <summary>
        /// A README beside the preset. The preset is otherwise a black box of
        /// YAML; this records the exact invocation so a failure can be
        /// reproduced by hand without reading the shim's source.
        /// </summary>
        public static string RenderReadme(Msys2Flavour flavour, string shellCmd, string shimExe)
        {
            var sb = new StringBuilder();
            sb.Append("# ").Append(flavour.Label).Append(" — DSH agent preset\n\n");
            sb.Append("Installed by the DSH MSYS2 installer. Reinstalling overwrites these files.\n\n");
            sb.Append("## What runs\n\n");
            sb.Append("Every agent command goes through `").Append(ShimExeName).Append("`, which invokes:\n\n");
            sb.Append("    \"`").Append(shellCmd).Append("`\" ")
              .Append("-defterm -no-start -use-full-path ").Append(flavour.ShellFlag)
              .Append(" -here -c \"<your command>\"\n\n");
            sb.Append("The shim exists because DSH's pwsh executor spawns a fixed argv\n");
            sb.Append("(`-NoLogo -NoProfile -NonInteractive -Command <cmd>`) with `pwshPath` as\n");
            sb.Append("argv[0] of a direct spawn — and a `.cmd` cannot be argv[0] (Node returns\n");
            sb.Append("EINVAL for it). The shim is a real executable that strips the PowerShell\n");
            sb.Append("encoding preamble, writes the command to a temporary script, and runs the\n");
            sb.Append("invocation above with that script as its command.\n\n");
            sb.Append("## Environment\n\n");
            sb.Append("The shim reads its configuration from the environment:\n\n");
            sb.Append("| Variable | Value |\n| --- | --- |\n");
            sb.Append("| `DSH_MSYS2_SHELL_CMD` | `").Append(shellCmd).Append("` |\n");
            sb.Append("| `DSH_MSYS2_MSYSTEM` | `").Append(flavour.Msystem).Append("` |\n\n");
            sb.Append("## Reproducing a failure by hand\n\n");
            sb.Append("From a Windows prompt (this needs an unconfined shell — see below):\n\n");
            sb.Append("    \"").Append(shimExe).Append("\" -Command \"uname -s; echo $MSYSTEM\"\n\n");
            sb.Append("## Why this preset is unconfined\n\n");
            sb.Append("MSYS2 cannot start under the Windows ACL sandbox. `usr\\bin` loads\n");
            sb.Append("`msys-2.0.dll`, whose startup creates the per-user named section\n");
            sb.Append("`CreateFileMapping S-1-5-21-<user>-1001.1`; a write-restricted token denies it\n");
            sb.Append("with Win32 error 5, so `bash.exe` dies before running anything:\n\n");
            sb.Append("    bash.exe: *** fatal error - CreateFileMapping S-1-5-21-...-1001.1, Win32 error 5.\n\n");
            sb.Append("The preset therefore pins `danger-full-access`.\n\n");
            sb.Append("- MSYS2 install root: `").Append(Path.GetDirectoryName(Path.GetFullPath(shellCmd))).Append("`\n");
            sb.Append("- Shim: `").Append(shimExe).Append("`\n");
            return sb.ToString();
        }

        /// <summary>
        /// Write one file with LF endings and no BOM. A BOM in a YAML file is a
        /// needless variable, and these files are read by YAML tooling.
        /// </summary>
        private static void WriteTextFile(string path, string content)
        {
            File.WriteAllText(path, content, new UTF8Encoding(false));
        }

        /// <summary>
        /// Install one flavour's preset directory.
        ///
        /// Each file is written to a temporary name and then moved into place,
        /// so an interrupted run cannot leave a half-written composition that
        /// DSH's discovery would report as a broken roster row.
        ///
        /// `shimExe` may be null, in which case the shim is compiled into the
        /// preset directory directly.
        /// </summary>
        public static InstallResult Install(
            Msys2Flavour flavour,
            string shellCmd,
            string presetRoot,
            string shimExe)
        {
            string presetDir = Path.Combine(presetRoot, flavour.PresetId);
            Directory.CreateDirectory(presetDir);

            var result = new InstallResult();
            result.Flavour = flavour;
            result.PresetDir = presetDir;

            string presetShim = Path.Combine(presetDir, ShimExeName);
            if (shimExe == null)
            {
                ShimBuilder.Build(ShimBuilder.SourcePath(), presetShim);
            }
            else if (!string.Equals(
                Path.GetFullPath(shimExe), Path.GetFullPath(presetShim), StringComparison.OrdinalIgnoreCase))
            {
                File.Copy(shimExe, presetShim, true);
            }
            result.Written.Add(presetShim);

            var files = new Dictionary<string, string>();
            files[CompositionFileName] = RenderComposition(flavour, shellCmd, presetShim);
            files[MetadataFileName] = RenderMetadata(flavour);
            files[ReadmeFileName] = RenderReadme(flavour, shellCmd, presetShim);

            foreach (KeyValuePair<string, string> entry in files)
            {
                string target = Path.Combine(presetDir, entry.Key);
                string temp = target + ".tmp";
                WriteTextFile(temp, entry.Value);
                if (File.Exists(target)) File.Delete(target);
                File.Move(temp, target);
                result.Written.Add(target);
            }

            return result;
        }

        /// <summary>
        /// Install several flavours, compiling the shim only once.
        ///
        /// `progress` is called as (flavour, index, total) before each flavour,
        /// so the GUI can narrate without this class knowing about WinForms.
        /// </summary>
        public static List<InstallResult> InstallAll(
            IList<Msys2Flavour> flavours,
            string shellCmd,
            string presetRoot,
            Action<Msys2Flavour, int, int> progress)
        {
            // Compile once into a scratch directory OUTSIDE the preset root.
            // DSH's discovery scans every directory under the preset root and
            // reports one without a composition as a broken roster row, so a
            // helper directory left there would show up as a mystery preset.
            string scratch = Path.Combine(
                Path.GetTempPath(), "dsh-msys2-shim-build-" + Guid.NewGuid().ToString("N"));
            string shim;
            try
            {
                shim = ShimBuilder.Build(ShimBuilder.SourcePath(), Path.Combine(scratch, ShimExeName));

                var results = new List<InstallResult>();
                for (int i = 0; i < flavours.Count; i++)
                {
                    if (progress != null) progress(flavours[i], i + 1, flavours.Count);
                    results.Add(Install(flavours[i], shellCmd, presetRoot, shim));
                }
                return results;
            }
            finally
            {
                // The per-preset copies are what matter; the scratch copy is
                // only a build cache for this one run, and it lives outside the
                // preset root so cleanup is purely hygiene.
                try { if (Directory.Exists(scratch)) Directory.Delete(scratch, true); }
                catch (Exception) { }
            }
        }

        /// <summary>Remove one preset directory. False when nothing was there.</summary>
        public static bool Uninstall(Msys2Flavour flavour, string presetRoot)
        {
            string presetDir = Path.Combine(presetRoot, flavour.PresetId);
            if (!Directory.Exists(presetDir)) return false;
            Directory.Delete(presetDir, true);
            return true;
        }

        /// <summary>Which of our presets are currently on disk.</summary>
        public static List<Msys2Flavour> Installed(string presetRoot)
        {
            var found = new List<Msys2Flavour>();
            foreach (Msys2Flavour flavour in Msys2Flavours.All)
            {
                string composition = Path.Combine(presetRoot, flavour.PresetId, CompositionFileName);
                if (File.Exists(composition)) found.Add(flavour);
            }
            return found;
        }
    }
}
